// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzHh70PPwWGF_RXVCJEFQfVeidYVH8oS4',
    appId: '1:578248543336:web:227360a74aa16087adffdd',
    messagingSenderId: '578248543336',
    projectId: 'be-social01',
    authDomain: 'be-social01.firebaseapp.com',
    storageBucket: 'be-social01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0j6kiLeNc6Dc31LG8aFwuCRd7jOA4ISk',
    appId: '1:578248543336:android:b090d64d8a0d7fd4adffdd',
    messagingSenderId: '578248543336',
    projectId: 'be-social01',
    storageBucket: 'be-social01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABL672yiwMFPlIo-GjayfLDp22ABa4wEo',
    appId: '1:578248543336:ios:8c2c83139ceb5724adffdd',
    messagingSenderId: '578248543336',
    projectId: 'be-social01',
    storageBucket: 'be-social01.appspot.com',
    iosBundleId: 'np.com.besocial.besocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABL672yiwMFPlIo-GjayfLDp22ABa4wEo',
    appId: '1:578248543336:ios:215c706930bc947eadffdd',
    messagingSenderId: '578248543336',
    projectId: 'be-social01',
    storageBucket: 'be-social01.appspot.com',
    iosBundleId: 'np.com.besocial.besocial.RunnerTests',
  );
}
